### ISSUE TITLE
Aggregation Fixes

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server-staging-terraform#152]
# Track new Attributes: 
 
## Global Attributes
 - osversion

## Event Specific Attributes
 - bucket background-checks count
   - 1-6
   - 6-12
   - 12-30
   - 30+
- Background-Process Duration
  - < 30 seconds
  - > 30 seconds < 1 minute
  - 1 min - 2 min 
  - 3 min - 4 min
  - 4 min - 6 min
  - 6 min - 8 min
  - 9 min - 10 min

**Comment by craigzour** [comment]
@CalvinRodo OS version attribute name is `osversion` and it will be different depending on the OS type.
- iOS will give something like "13.1.2"
- Android will give something like "24" (which is the Android API level)

**Comment by CalvinRodo** [comment]
Completed in PR #154
