### ISSUE TITLE
QR Code - New In-App Metrics

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server-staging-terraform#199]
Metrics are identified here https://docs.google.com/document/d/1cquRya5pFDiaOFnKDh9MSJqF4s0eiF2yAOthflj1moI/edit

**Comment by CalvinRodo** [comment]
Blocked by lack of Schema

**Comment by patheard** [comment]
This has been addressed by:

* cds-snc/covid-alert-metrics#106
* cds-snc/covid-alert-metrics#120
