### ISSUE TITLE
New QR code metrics

### ISSUE THREAD

**Issue by craigzour** [cds-snc/covid-alert-server-staging-terraform#213]
New QR code metrics will be introduced with https://github.com/cds-snc/covid-alert-app/pull/1533.

Here is the list of changes (to be confirmed):
* Added “qr-code-successfully-scanned” metric
* Added “exposed-outbreak” metric
* Replaced existing “otk-entered” (only internally stored version of this metric can still be pushed to the server) metric with “otk-entered-v2”
    * Associated value of “isUserExposed” in the payload has been changed and  is now a string that can be equal to “”, “proximity”, “outbreak” or “proximity,outbreak”

**Comment by craigzour** [comment]
Here is an example of a payload that can be sent to the server:
{
   "metricstimestamp":1619799186901,
   "appversion":"1.1.8",
   "appos":"ios",
   "osversion":"14.3",
   "manufacturer":"Apple",
   "model":"unavailable",
   "androidreleaseversion":"unavailable",
   "payload":[
      {
         "identifier":"qr-code-successfully-scanned",
         "region":"QC",
         "timestamp":1619712079218
      },
      {
         "identifier":"qr-code-successfully-scanned",
         "region":"QC",
         "timestamp":1619712243383
      },
      {
         "identifier":"exposed-outbreak",
         "region":"QC",
         "timestamp":1619712387437
      },
      {
         "identifier":"otk-entered-v2",
         "region":"QC",
         "timestamp":1619712574087,
         "withDate":"false",
         "isUserExposed":"outbreak"
      },
      {
         "identifier":"active-user",
         "region":"QC",
         "timestamp":1619799185777
      }
   ]
}

**Comment by CalvinRodo** [comment]
Because  `qr-code-successfully-scanned` and  `exposed-outbreak` don't have associated attributes they just work.

**Comment by CalvinRodo** [comment]
`withDate` and `isUserExposed` were also tracked so this is done.
