### ISSUE TITLE
Fail PR when TF Format fails

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server-staging-terraform#78]
Right now formats are failing but PR is passing so tf fmt failing needs to block a PR being able to merge.

**Comment by patheard** [comment]
Related to cds-snc/covid-alert-server-demo-terraform@24d887df

**Comment by patheard** [comment]
See cds-snc/covid-alert-server-demo-terraform#41 for fix

**Comment by patheard** [comment]
Will need to wait until #212 lands
