### ISSUE TITLE
A record pointing to Metric Endpoint

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server-staging-terraform#81]
The metrics endpoint needs to be behind a stable endpoint. 

This can be done by adding a cname record to https://github.com/cds-snc/covid-alert-server-staging-terraform/blob/master/server/aws/route53.tf

This url should be in the format: 
```terraform
metric.${aws_route53_zone.covidshield.name}
```

**Comment by maxneuvians** [comment]
Closed in #83
